### ISSUE TITLE
Disable software-update notifications

### ISSUE THREAD

**Issue by XioNoX** [nttgin/BGPalerter#1058]
**Describe the bug**
Can't find a way to disable the `BGP alert: software-update` notifications

**Provide an example**
We have configured BGPalerter to send its notifications (considered urgent) to all our SRE team.
However we started to receive non urgent notifications as well `BGP alert: software-update` which are disruptive to the team.

Based on https://github.com/nttgin/BGPalerter/blob/ae5fcc744e229bc50d91993c97e5cc799912f1d5/docs/configuration.md?plain=1#L18
It is not possible to disable such "every 10 days" emails. Asking everybody to add filters is not sustainable and risks blocking valid notifications.

**Expected behavior**
There should be a configuration option to disable such notifications, it being opt-in seems more appropriate as well but that's a personal call.

Thanks

**Comment by b4ldr** [comment]
sorry for the duplicate but +1 from me :)

**Comment by massimocandela** [comment]
Hey,

By default BGPalerter creates 2 user groups `default` and `noc`.
`default` is used for administrative communications about the software (e.g., updates, errors), `noc` is used only for network incidents (you can also create other user groups).

If you noc is receiving software updates notification, it's because this default configuration was wiped and the `default` user group is used for both cases. Read more about this in the documentation [here](https://github.com/nttgin/BGPalerter/blob/main/docs/usergroups.md), also explained [here](https://github.com/nttgin/BGPalerter/blob/main/docs/reports.md#reports). 

I prefer to not introduce a way to disable default notifications, since these notifications should not reach the noc in the first place, but an admin user/log file. I think this project reaches better it's community goals by reminding users to keep the monitoring software up to date and patched.

**Comment by b4ldr** [comment]
@massimocandela thanks for the response

> I prefer to not introduce a way to disable default notifications, since these notifications should not reach the noc in the first place, but an admin user/log file. I think this project reaches better it's community goals by reminding users to keep the monitoring software up to date and patched.

I think this is great for users that are using the git version however as per the issues i raised:

>when packaging software for linux distributions it is common to pin software to a specific version and only backport security fixes to ensure stability as such it would be desirable to completely disable this option in such software. Further i suspect some would benefit from having lower (or even higher) values here

thanks john
AS14907 - Wikimedia Foundation

**Comment by XioNoX** [comment]
In addition to what John mentioned, sending `default` to `/dev/null` risks missing important notifications.
If you prefer not adding a know to silence `software-update` would it be a good compromise to add a mechanism to separate those messages from other potential important notifications?
Thanks

**Comment by massimocandela** [comment]
Debian releases will now follow normal releases automatically. This is the best course of action instead of disabling update notification.
