### ISSUE TITLE
v1.33.0 RAM requirements check seems too aggressive

### ISSUE THREAD

**Issue by mfld-pub** [nttgin/BGPalerter#1270]
After upgrading from v1.32.0 to v1.33.0 service fails to start claiming there is not enough RAM.

Using the static binary on Debian 12.

```
Mar 15 12:55:42 rel bgpalerter-linux-x64[1827318]: /snapshot/BGPalerter/dist/index.js:107
Mar 15 12:55:42 rel bgpalerter-linux-x64[1827318]:       throw new Error("You need 4GB or RAM to run BGPalerter");
Mar 15 12:55:42 rel bgpalerter-linux-x64[1827318]:       ^
Mar 15 12:55:42 rel bgpalerter-linux-x64[1827318]: Error: You need 4GB or RAM to run BGPalerter
```

v1.32.0 ran perfectly on this instance for months. With v1.33.0 being less memory intensive there should be even less of an issue. 

Should this not run ? 

```
rel:/opt/bgpalerter# free -mt
               total        used        free      shared  buff/cache   available
Mem:            3823         671        2080           6        1071        2867
Swap:           4095           0        4095
Total:          7919         671        6176
```

**Comment by massimocandela** [comment]
Hi @mfld-pub,

I understand your concern. However, the amount of memory is affected by various factors, both related to what and when you are monitoring (e.g., in a moment where there is a great amount of BGP updates, like an instability). In the past several users reported crashes due to memory. I decided to set a default safe threshold for everybody instead of opening the door to the possibility that BGPalerter crashes in the moment you need it the most. The memory requirement is for the entire OS, not for the process (where you are running other processes in parallel as well). Overall, the requirement for the VM is contained for the type of service offered.
