### ISSUE TITLE
Disable "new version" updates

### ISSUE THREAD

**Issue by themitchy** [nttgin/BGPalerter#189]
**Describe what you would like to achieve**
I would like to disable the alerts for a new version being available (not just the first check at boot).

**Describe why the current solution (if any) is not satisfactory**
I don't want our customers to get this notification.

**Provide an example**
It is sent to all channels every time the monitor fires.

**Comment by massimocandela** [comment]
Hello @themitchy,

If you send alerts to customer you should create groups and never rely on the 'default' user group.
Look for "group" in prefixes.yml ([doc](https://github.com/nttgin/BGPalerter/blob/master/docs/prefixes.md#generate)) and in the [reports](https://github.com/nttgin/BGPalerter/blob/master/docs/configuration.md#reports).

You can create a group for each user and prefix pair, in a way to notify the correct user for each prefix. The default group can be used for administrative and error communications, so it's not the best way to expose this to customers. I will improve the documentation on this! Thanks.

I understand anyway your specific request. Please, try to define at least another user group, which is the correct way to go. I would like to postpone such feature to disable alerts about new updates because I believe it is important to be promplty notified of any security update available.
