### ISSUE TITLE
Reporting capabilities of AS path matching

### ISSUE THREAD

**Issue by jesk78** [nttgin/BGPalerter#272]
Cheers,

seems I either misunderstand the path match reporting mechanisms or I need to investigate into enhancing/fixing this perhaps.

Background:
I send an UDPATE of one of our prefixes into the DFZ. For that prefix I did configure a path match of '$MYASN' in prefixes.yml.

The resulting report of this UPDATE is:

- always just a single report, doesn't matter how many different paths via/to $MYASN do exist
- ${summary} is expanded to matchDescription + "on prefix $PREFIX 1 times"
- ${earliest} and ${latest} expanded
- ${pathNumber} and ${path} expanded (BUT always just to a single one eg. "Top 1 most used AS paths: [3356,$MYASN]")
- no other expansions are possible, the above is the maximum possible to get out of it

My main use case is reporting me any occurence of $MYASN being suddenly reachable through major/transit-free ASNs, multiple times, in noncontinous fashion (leakages). But for testing purposes all what I do is matching on $MYASN without any regex.

What I would expect to see is _all_ UPDATES matching the regex being reported. You could be able to see where a leak or any other regex match was seen, by ${peer} and also seeing the AS path of all those UPDATES spreading through the DFZ. You would be able to see the impact of that. Currently all you see is *one* PATH where the UPDATE matching the regex was seen, but not even from which peer.

What do you think, missing feature, wrong usage or bug? I'm out of clue for now, but continue to feel some love for BGPalerter, so would like to get more out of it.

**Comment by massimocandela** [comment]
Hi @jesk78,

By default, BGPalerter is instructed to report a single alert for each monitored issue. 
This is the most common use case in order to reduce noise and make the alerts actionable.
(e.g. if you have a hijack you don't want to receive 600 messages, one for each peer detecting the hijack).
Which is more inline with the idea to inform you asap when something happens more than giving you a complete map of it (also because there is no way to define "complete").

For your use case tho, this default configuration is not ideal. What you could do:
Option 1:
- Imagine it would be enough for you to receive a list of 50 paths used. Increase the ` thresholdMinPeers` parameter of `monitorPath`([here](https://github.com/nttgin/BGPalerter/blob/bcb6ba8934a978b62b6626107c0c423be7f91792/config.yml.example#L32)) to 50. Increase the `showPaths` value to 50 for the report of interest (e.g. [here](https://github.com/nttgin/BGPalerter/blob/bcb6ba8934a978b62b6626107c0c423be7f91792/config.yml.example#L75) if you are using email). 
With this solution, you will receive a cumulative alert as soon as you reach 50 peers reporting the same alert (and so also 50 paths). You will not receive any alert if the update doesn't reach 50 peers (which it would mean it's visibility is really limited). This is also what happens with the other monitoring.

Option 2: 
- Decrease `notificationIntervalSeconds` to something small enough (e.g. 1 second). Be aware that this means you will be receiving an alert every single time the path is matched. I would suggest to use another instance of BGPalerter for this type of monitoring in order to don't affect the other monitors.

Possible options which require changes to the code:

Option 1:
- We could define a `delay` parameter which essentially prevents the alert to be sent immediately. The delay (in seconds) would allow the monitor to collect a set of paths. After such delay the paths are included in the alert, the alert sent and not repeated again before `notificationIntervalSeconds` expires. So imagine you would set the `delay=30`, after 30 seconds from the first received update you will receive an alert. The alert will contain `Top X most used AS paths` where X is the amount of path seen by BGPalerter in 30 seconds.

Option 2:
- We define a new key for the path matching alert [here](https://github.com/nttgin/BGPalerter/blob/bcb6ba8934a978b62b6626107c0c423be7f91792/src/monitors/monitorPath.js#L103). The first parameter of the `publishAlert` method is the key which is used to group together alerts and avoid duplicates. As you can see from the linked code, at the moment this parameter is the prefix matched. You could use for example the `pathString` instead (which it will be always different for each path). It would essentially behave like the Option 2 above without the need to run it on a separated instance to avoid other monitors to adopt the same behavior. You will receive an alert for each path matched. This is more an ad-hoc change if you are running the code.

**Comment by jesk78** [comment]
Massimo, thanks for providing those details and also possible options.

The thresholdMinPeers options has - as you pointed out - some serious drawback which makes it not very suitable for this. In case of setting the notificationIntervalSeconds to 1 would that really mean that it would react really on every single message? Even if when multiple messages are received in a single second? I suspect that by setting it to 1 it will still miss events, while it will make some sort of sophisticated aggregation support required in the systems receiving them from BGPalerter (which is not really possible when using for example email, as in my case).

So if you ask me your suggested delay parameter to aggregate events into single alerts, makes a lot of sense for me - very beneficial in many situations, providing alerts with more granular information, helping to detect location and scope of your prefixes going ham.

I suppose that aggregating events into single alerts by using a timer is not something totally trivial to bring into the code. But anyway I will try to think about the feasibility for me patching this in.

**Comment by massimocandela** [comment]
The feature of the delay is not a bad idea indeed. Not sure how easy it is but I'll try to arrange something as soon as I have some time. Contributions are welcome.

In the meanwhile I would use the `thresholdMinPeers` set to a "reasonable value" (no idea which, I would keep it below 60 and tune it from there). While it is true that you will not receive alerts if you don't reach such threshold, it is also true that for your use case (especially leaking in tier1) you would easily have a visibility of more than 50 peers (which is a small fraction of the total available).

**Comment by jesk78** [comment]
Yup, should be ok for that. But you never know. Just short inconsistency in policy with immediate fix (seen that) could mean only reaching a subset of those peers.
