### ISSUE TITLE
reportSyslog doesn't work

### ISSUE THREAD

**Issue by pistonov** [nttgin/BGPalerter#285]
I have 2 options int reports section and reportFile is recorded successful but no syslog message.

reports:
  - file: reportFile
    channels:
      - hijack
      - newprefix
      - visibility
      - path
      - misconfiguration
    params:
      persistAlertData: true
      alertDataDirectory: alertdata/

  - file: reportSyslog
    channels:
      - hijack
      - newprefix
      - visibility
      - path
      - asn-monitor
      - misconfiguration
    params:
      host: localhost
      port: 555
      templates:
        default: "++BGPalerter-3-${type}: ${summary}|${earliest}|${latest}"
        hijack: "++BGPalerter-5-${type}: ${summary}|${prefix}|${description}|${asn}|${newprefix}|${neworigin}|${earliest}|${latest}|${peers}"
        newprefix: "++BGPalerter-4-${type}: ${summary}|${prefix}|${description}|${asn}|${newprefix}|${neworigin}|${earliest}|${latest}|${peers}"
        visibility: "++BGPalerter-5-${type}: ${summary}|${prefix}|${description}|${asn}|${earliest}|${latest}|${peers}"
        misconfiguration: "++BGPalerter-3-${type}: ${summary}|${asn}|${prefix}|${earliest}|${latest}"

**Comment by massimocandela** [comment]
Hi @pistonov,

I need more information in order to help you.
The reportSyslog module is currently working on some of my BGPalerter instances. 
I covered it with some tests (see [dev](https://github.com/nttgin/BGPalerter/commits/dev)). From the next release you will be able to get more specific errors in case the connection to syslog fails.

If you want to run the tests yourself on your machine, do:
```bash
git clone git@github.com:nttgin/BGPalerter.git
git checkout dev
npm install
npm run test-reports
```

I believe your problem is due to a misconfiguration.
