### ISSUE TITLE
Empty prefixes.yml file generated - Temporary RIPEstat outage

### ISSUE THREAD

**Issue by spheron1** [nttgin/BGPalerter#312]
**Describe what you would like to achieve**
Option for providing verbose output for debugging when generating prefixes

**Describe why the current solution (if any) is not satisfactory**
There seems to be a problem with stat.ripe.net at the moment which is causing all generated prefix lists to be empty. This obviously isn't a problem caused by BGPalerter, but it may have been easier to troubleshoot if there was a way to get more information on the data which is being returned from stat.ripe.net and what BGPalerter is doing when processing that data.

**Provide an example**
This is what I see currently, which doesn't really give much to go on:

```
~# bgpalerter generate -a 41000 -o prefixes.yml
Done!
~# cat prefixes.yml
{}
```

Ideally there would be something like a --verbose or --debug option which would help to see the details of what is happening behind the scenes and track down where the problem is.

Unfortunately as the connection to stat.ripe.net is over HTTPS, I couldn't even see the data in a packet capture.

**Your information**
Edward Dore, Freethought Internet Limited, AS41000

**Comment by massimocandela** [comment]
> This affects the generation of new configurations but not the monitoring of already available configurations.

Hi @spheron1,

The auto-configuration already has a verbose output which shows you all the steps and all the prefixes detected.
Also, it reports any error occurred while downloading the data.

The problem here is that at the moment the API of RIPEstat is "working properly" but reporting an empty dataset (or with too old data). Essentially the API is reporting always that the provided AS is not announcing anything at the moment (which could be true in same cases). I honestly would not know what to do in this case.

I'm not aware of other APIs providing the same information of RIPEstat (otherwise we could do some redundancy).

Luckily RIPEstat failures of this scale are rare. I presume it will be fixed soon.
I contacted the RIPE NCC staff, I will keep you informed.

In the meanwhile let me know if you need any help with the [manual configuration](https://github.com/nttgin/BGPalerter/blob/master/docs/prefixes.md#prefixes-fields).

**Comment by spheron1** [comment]
Hi @massimocandela,

As I said, I'm aware that the underlying cause of this particular issue is with RIPEstat and not BGPalerter, but if there was a way for the user to get more verbose data on what is happening behind the scenes then I could have been aware of that a lot sooner and not spent so much time trying to work out what I was doing wrong.

I don't believe this is limited to this particular case either. I think it would be generally useful to have verbose/debugging data available to show what was retrieved from RIPEstat to help track down any differences between what is expected and what is actually happening.

This could potentially be done via two levels - the first to show a summary of what has been retrieved and how it was processed and then a second which gives the actual raw response from RIPEstat.

**Comment by massimocandela** [comment]
In addition to writing which prefixes are detected (already available), I added:
* A warning, as suggested in my first message, about the list of prefixes being empty.
* The option `-D` to enable the debug mode. You will receive all http queries issued (urls).
* The option `-H` to generate the prefixes with historical visibility data (prefixes announced in the last week).

I think this is a practical and effective solution.

**Comment by spheron1** [comment]
That's great, thank you very much @massimocandela 👍

**Comment by massimocandela** [comment]
Btw, RIPEstat is working again.
