### ISSUE TITLE
Match Format Difficult to not hit superstring ASNs

### ISSUE THREAD

**Issue by TheBlueMatt** [nttgin/BGPalerter#318]
Admittedly I'm going based off the docs here, so feel free to tell me off (or I'll help update the docs!), but from what I can tell, its hard to match, eg, Cogent AS174 without also matching Bob's Hosting ASXX174. Specifically, if I want to match for "transits Cogent to AS397444", I would naively write ".\*174,397444$" (eg as is recommended at https://github.com/nttgin/BGPalerter/blob/master/docs/configuration.md#monitorpath), but from what I can tell that would also match "1174,397444", which isn't what I want. I could match ".\*,174,397444$", but that wouldn't match simply "174,397444".

One easy fix would be to add a "," prefix in the as path that is passed to the regex filter, allowing the extra-comma example to work, though of course this has backwards-compatibility questions (https://github.com/nttgin/BGPalerter/blob/master/docs/prefixes.md#optimized-regular-expressions-for-as-path-matching suggests using "^" in a few places, which would break on this, as far as I understand).

**Comment by massimocandela** [comment]
Originally, the RIPE RIS team introduced some particular strings similar to regex (but not regex) that were supposed to be easier to use (and probably lighter on their side). Those "regex" are described [here](https://ris-live.ripe.net/manual/) and they take care transparently of the comma, this is why the examples in the doc were "wrong regex".

I removed that feature and the doc because there is no longer any technical reason to support them.

I now allow only for real regex, [documentation here](https://github.com/nttgin/BGPalerter/blob/dev/docs/path-matching.md).

> One easy fix would be to add a "," prefix in the as path that is passed to the regex filter, allowing the extra-comma example to work, though of course this has backwards-compatibility questions

There is no need for this, regular expressions handle that case, see doc for examples.
