### ISSUE TITLE
Possible Issue with self signed certificate and reportHTTP

### ISSUE THREAD

**Issue by neok0** [nttgin/BGPalerter#405]
**Describe the bug**
I enabled the reportHTTP module to send alerts to Mattermost channel. Alerting to file does work, however no alerts are send to Mattermost. 
I'm using the docker version, I went into the container to check if there is a route to the Mattermost webhook via simple wget request. 
Wget prompted me with the error message `certificate verification failed: unable to get local issuer certificate `which is due to the fact that I'm using a self signed certificate for this Mattermost server.

There are no other errors logged to the errors-log file, therefore my currently theory is that the reportHTTP option silently fails because of the missing trusted ca certificate.

**Provide an example**
Unfortunately, there is not much I can show, I used the exact Mattermost configuration sample provided in the docs. There are also no errors shown in the error.logs files. 

**Expected behavior**
The simplest solution ofc, would be to have a switch to disable ssl verification for testing purposes. 
However, there should be an option to use a dedicated ca certificate for the verification. 

**Are you using the binary or the source code?**
the docker container version 1.26.2

**Comment by massimocandela** [comment]
Hi @neok0,

The real bug here is the query silently failing. 
This has been addressed in 1.27.0, which will go out soon. I also tested it with both a self-signed certificate and an expired certificate on 1.27.0 and I correctly see the errors in the logs (sometimes the error will appear some seconds later in the file because there is a retry approach for http(s) queries).
Thanks for reporting!

For test purposes you can run the application with `NODE_TLS_REJECT_UNAUTHORIZED=0 ./bgpalerter-linux-x64` which will not reject failing https connections. I don't suggest to do that in production. I'm not planning to support private CAs for now.
