### ISSUE TITLE
Notification options

### ISSUE THREAD

**Issue by mmarin11** [nttgin/BGPalerter#500]
Hi Massimo

I'm trying to notify BGP alerts to different teams. For example if an ASN X advertises a new prefix that was not previously defined in the prefixes.yml file, send a HTTP alter to team A, but if ASN Y does the same thing, send an alert to team B. However it looks like regardless of the group definition, BGP alerter only notifies to the noc group.

Attached is a screenshoot of the config files.

I would appreciate if you can help me to verify if something is wrong with the config.

![image](https://user-images.githubusercontent.com/40378669/109319318-f7111f80-780b-11eb-9447-d649bd220764.png)

![image](https://user-images.githubusercontent.com/40378669/109319827-8b7b8200-780c-11eb-8916-df76f9491c14.png)

**Comment by massimocandela** [comment]
Hi @mmarin11,

In prefixes.yml, before the `options` section you have the list of monitored prefixes. That list has also a user group defined for each prefix. Monitoring by AS means that whatever is not matched in the prefix list is matched by the AS rule. Both rule can have different user groups by design. 

I believe your prefix list has `noc` as user group for the prefix rules of 32098 and 55259 and so the messages are sent there. This may have happened if you auto configured everything with noc (default) and after changed manually only the items in the AS list).

Please, read the documentation about [user groups](https://github.com/nttgin/BGPalerter/blob/master/docs/usergroups.md) and about how to [generate the prefix list correctly](https://github.com/nttgin/BGPalerter/blob/master/docs/prefixes.md#generate) (in particular, see options m, A, and g)

**Comment by massimocandela** [comment]
Let me know if everything works now or if you have other questions.
