### ISSUE TITLE
Error retrieving RPKI information from Routinator

### ISSUE THREAD

**Issue by tverschuren** [nttgin/BGPalerter#606]
BGPAlerter error retrieving RPKI information from Routinator http service.

BGPalerter appends ?client=ntt-bgpalerter to the url, which is not accepted by Routinator.

Testing with curl shows http://127.0.0.1:8323/json results in RPKI data, while http://127.0.0.1:8323/json?client=ntt-bgpalerter results in a "Bad Request" response.

Find the relevant log attached. [log.txt](https://github.com/nttgin/BGPalerter/files/6840217/log.txt)

**config.yml**
rpki:
  vrpProvider: api
  preCacheROAs: true
  url: http://127.0.0.1:8323/json

**Versions**
Debian 10
BGPalerter 1.28.1
Routinator 0.9.0

Is it possible to prevent bgpalerter from appending the client part?

Let me know if more info/logs/testing is needed.

Thomas Verschuren
IP Visie Networking (AS198089)

**Comment by massimocandela** [comment]
Hi @tverschuren,

Thanks for reporting this. I'm not sure since when this started to happen.
I pushed a patch but I don't know when I can release it in production.
In the meanwhile, you can:
1) create a cronjob to download the api output of Routinator and use a vrpFile configuration in BGPalerter; or
2) deploy/compile the patched version currently available in the dev/release branch.

**Comment by massimocandela** [comment]
released in v1.28.2
