### ISSUE TITLE
Documentation report-http pruned

### ISSUE THREAD

**Issue by cadirol** [nttgin/BGPalerter#717]
Hi
By random, i found that the Rocketchat Config snippets are vanished from doc file:
https://github.com/nttgin/BGPalerter/blob/main/docs/report-http.md
See PR #704 

Any reason?

**Comment by massimocandela** [comment]
Hi @cadirol,

Since your PR no new release has been published.
Your PR is merged in `dev` [here](https://github.com/nttgin/BGPalerter/blob/dev/docs/report-http.md), the next release will merge it in `main`. Here you can find more info about the [git flow](https://github.com/nttgin/BGPalerter/blob/main/docs/release-process.md).
