### ISSUE TITLE
On withdrawal-detection the peer is missing 

### ISSUE THREAD

**Issue by cadirol** [nttgin/BGPalerter#718]
**Describe the bug**
On a withdrawal-detection report the following summary is sent out. The Peer is known, but the peer is not stored in a variable like ${peer}
`The prefix 185.63.148.0/22 (No description provided) it's no longer visible (withdrawn) from the peer 185.255.53.202`

**Provide an example**
Acording to this: https://github.com/nttgin/BGPalerter/blob/main/docs/context.md  
withdrawal-detection Summary:  
`The prefix 185.63.148.0/22 (No description provided) it's no longer visible (withdrawn) from the peer 185.255.53.202`

The Prefix (185.63.148.0/22) is accessible with ${prefix}. But the affected peer (185.255.53.202) is not stored in a Variable. 

**Expected behavior**
i expect a Variable for peer like ${prefix}

**Are you using the binary or the source code?**
Binary

**Your information**
AS15576

**Comment by massimocandela** [comment]
In general, summaries can report data not exported into the context. The reason why ${peer} is not there is that usually alerts contain several peers. Especially visibility alerts they can contain hundreds of peers (and listing all the IPs is not really helpful). What you reported is the summary of an alert with only one peer, which is a special case treated differently: I check if there is only one peer and I report it, I report the total number otherwise. 

What I can do is to add a new variable having comma-separated list of peers. Something like ${peerlist} that is replaced with "185.255.53.202, 185.255.53.203, 185.255.53.204". However, this will not affect the current text reported by the alerts, but the variable can be used in templates. Would that work?  (Due to the potentially long list of IPs, I will have to asses the impact on resource usage before to promote this to production).

**Comment by cadirol** [comment]
hi
> What you reported is the summary of an alert with only one peer, which is a special case treated differently: I check if there is only one peer and I report it, I report the total number otherwise.
That's a good idea! If only one peer report it, otherwise display only the number of peers!

> What I can do is to add a new variable having comma-separated list of peers.
Good idea as well! This list can be parsed in further tools/syslog/Elasticsearch/whatever

Cool, thank you

**Comment by massimocandela** [comment]
Hi @cadirol,

> Good idea as well! This list can be parsed in further tools/syslog/Elasticsearch/whatever

The list is already provided in the data object for the reports. E.g., see the output attached [here](https://gist.github.com/b4ldr/22e4c36dcfa34d3abaa42d2a2a335739#file-out-json-L5). In the data object you can see all the BGP messages (and their peer) that triggered the alert.

I think I misunderstood your request before. Since BGPalerter in the alert summary already implements the "if only one peer report it, otherwise display the number of peers", I would say we are probably good like this; if not, let me know.
