### ISSUE TITLE
Cannot read property 'map' of null

### ISSUE THREAD

**Issue by donwito** [nttgin/BGPalerter#878]
Hey,

I'm trying to generate the prefixes.yml file for a specific prefix and I'm getting this error:

```
./bgpalerter-linux-x64 generate -p 135.84.59.0/24 -o prefixes.yml
Generating monitoring rule for 135.84.59.0/24
Something went wrong TypeError: Cannot read property 'map' of null
```

I've tried with several different /21, /22, /24 on 2 separate Ubuntu machines and one MacOS laptop. All with the same result.

Is this something on my end or is RIS returning some empty results?

**Comment by massimocandela** [comment]
Hi @donwito,

This is fixed in the `dev` branch and it will go into production with the next release. Thanks for reporting.

However, I would suggest you to generate an entire config based on the AS (just remove `prefixes.yml`and the auto-config will start on the next run). Partial configs don't provide the same level of monitoring and are more prone to be noisy. Start with a complete config based on the AS and use the `ignore` option on prefixes you don't want to receive alerts for.
