### ISSUE TITLE
error: 1006

### ISSUE THREAD

**Issue by edugas** [nttgin/BGPalerter#9]
Hello,

I'm running BGPAlerter on two Ubuntu 18.04.3 LTS VMs and keep getting "error: 1006" after some time. Nothing in the error log.

**Comment by Epaphus** [comment]
I see the same on a Debian 10 VM, Looking at netstat after the "error: 1006" bgpalerter no longer has a connection to RIPE RIS

**Comment by massimocandela** [comment]
WebSocket error 1006 is a low level error that means the connection was closed abnormally. Unfortunately it can happen for a lot of reasons, including: client exceptions during connection and error during HTTP Upgrade to WebSocket (e.g. the server didn't answer properly). I will investigate on it. As a first step I need to reproduce it: how many prefixes are you monitoring? Do you have carefulSubscription set to true? After how much time you get the error? Thanks

**Comment by smfeldman** [comment]
The same thing happened to me.  I'm running the linux binary.

22 prefixes monitored, `carefulSubscription: true` set.
It ran for just under 9 hours, starting at 16:45 UTC yesterday and ending at 01:40 today.

**Comment by edugas** [comment]
I monitor 20 prefixes. Using carefulSubcription too.

**Comment by massimocandela** [comment]
I pushed a possible fix/workaround, including new binaries.
What I added is:
1) periodic pings - months ago the RIS server was dropping connections for inactivity, but I already reported this and it got fixed. At that time, the temporary fix was to do a periodic ping to the server.
I introduced again this feature even if I believe this is no longer the case.
2) auto reconnect - if the connection drops for whatever reason, the client tries to reconnect again in 5 seconds.

In my tests, the way I was able to reproduce the error 1006 was to disconnect (and reconnect after some seconds) the VM. I know this sounds obvious, but please check that your machine is not  loosing connectivity at some point.

Please, let me know if with the new binaries the issue is mitigated.

**Comment by massimocandela** [comment]
I just realised the auto-reconnect feature is not implemented properly and in some cases it may not work. So please wait for a new fix.

**Comment by massimocandela** [comment]
Now it should be all done. Let me know.

**Comment by smfeldman** [comment]
I'm still seeing occasional error 1006 messages (about once per day), but it seems to be successfully reconnecting now.
